django_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('tasks/create/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/<int:task_id>/complete/', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('logout/', views.sesion, name='logout'),
    path('login/', views.iniciar, name='login')

]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + '- by' + self.user.username

tasks/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'important']

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.http import HttpResponse
from .forms import TaskForm
from .models import Task
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html',{
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request,user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'signup.html',{
                    'form': UserCreationForm,
                    "error": 'Username already exists'
                })
        return render(request, 'signup.html',{
                    'form': UserCreationForm,
                    "error": 'Password do not match'
                })

@login_required
def tasks(request):
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=True)
    return render(request, 'tasks.html',{
        'tasks': tasks
    })

@login_required
def tasks_completed(request):
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=False).order_by('-datecompleted')
    return render(request, 'tasks.html',{
        'tasks': tasks
    })
    
@login_required
def create_task(request):
    if request.method == 'GET':
        return render(request, 'create_task.html', {
            'form': TaskForm
        })
    else:
        try:
            form = TaskForm(request.POST)
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect('tasks')
        except ValueError:
            return render(request, 'create_task.html', {
            'form': TaskForm,
            'error': 'Please provide valida data'
        })

@login_required
def task_detail(request, task_id):
    if request.method == 'GET':
        task = get_object_or_404(Task, pk=task_id, user=request.user)
        form = TaskForm(instance=task)
        return render(request, 'task_detail.html',{
        'task': task,
        'form': form
    })
    else:
        try:
            task = get_object_or_404(Task, pk=task_id, user=request.user)
            form = TaskForm(request.POST, instance=task)
            form.save()
            return redirect('tasks')
        except:
            return render(request, 'task_detail.html',{
                'task': task,
                'form': form,
                'error': 'Error updating task'
            })

@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        task.datecompleted = timezone.now()
        task.save()
        return redirect('tasks')

@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks')

@login_required
def sesion(request):
    logout(request)
    return redirect('home')

def iniciar(request):
    if request.method == 'GET':
        return render(request, 'login.html',{
            'form': AuthenticationForm
        })
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
                return render(request, 'login.html',{
                'form': AuthenticationForm,
                'error': 'Username or password is incorrect'
            })
        else:
            login(request, user)
            return redirect('home')

            

tasks/templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <title>Django CRUD</title>
    </head>
    <body>
        <div>
        <header class="header">
            <a href="/home" class="logo">Home</a>
                <nav class="navbar">
                    {% if user.is_authenticated %}
                    <a href="/tasks">Tasks Pending</a>
                    <a href="/tasks_completed/">Tasks Completed</a>
                    <a href="/tasks/create/">Create Task</a>
                    <a href="/logout">Logout</a>
                    {% else %}
                    <a href="/signup">Signup</a>
                    <a href="/login">Login</a>
                    {% endif %}
                </nav>
        </header>
    </div>

        {% block content %}
        {% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

tasks/templates/Home.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Home</title>
    </head>
    <body>
        <div class="container-xxl">
            <div class="row">
                <div>
                    <br>
                    <h1 class="titulohome">Home</h1>
                    <br>
                </div>
                <div class="row">
                    <div class="col-6 text1">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa voluptatem cupiditate similique minima deleniti laudantium vero delectus impedit beatae! Debitis reprehenderit, cupiditate eligendi vero a esse culpa fugit consequatur inventore?
                        Eveniet inventore quae dolore magnam! Voluptas minus mollitia commodi eum adipisci impedit suscipit dolorem, optio placeat perspiciatis quibusdam delectus animi sed est dolor. Excepturi, accusamus natus quae repellat eveniet veniam!
                        Iure, laborum ratione. Nemo quis officia laborum vero aperiam totam at numquam, aliquid quo quae aliquam magni dolores repudiandae id beatae soluta debitis vel consequatur repellendus. Sed asperiores ducimus officiis?
                        Numquam, reprehenderit. Eius perferendis, provident alias voluptates laudantium facilis quis totam corporis, necessitatibus, repellendus obcaecati consequuntur nulla dolor quae illum tempora. Consequatur totam placeat temporibus voluptate alias maxime molestiae expedita?
                        </p>
                    </div>
                    <div class="col-6">
                        <img class="imagen1" src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*hxuh2QUsINTJ5Dh2cmy-lw.png" class="img-fluid" alt="">
                    </div>
                    <div class="col-12 text1">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt consectetur soluta perspiciatis expedita? Odio esse possimus cupiditate dicta inventore sunt. Fugit neque eius rem dolore esse dolor, temporibus nobis quas.
                        Obcaecati, quo illo explicabo fugiat beatae iusto doloribus error quasi numquam perferendis id expedita eaque. Magni at eius natus aliquam iusto assumenda saepe quae, vel, doloremque, qui nostrum maiores? Natus.
                        Quam, beatae culpa. Amet quidem iusto repellat soluta. Nesciunt non ipsa explicabo autem cupiditate natus veniam numquam itaque neque dicta nihil in veritatis, error, repellat blanditiis ab optio atque minus!
                        Quis laudantium aspernatur praesentium ut. Repellendus, inventore, possimus asperiores molestias fugit consequatur, debitis ab alias sunt veritatis dolor deserunt. Earum dolorem asperiores nulla voluptatem et rerum, incidunt est ipsam aliquid?
                        Officia, tempore et id possimus quasi voluptas corrupti alias, earum ut cupiditate consectetur tenetur dolore maiores amet? Repudiandae aliquam aut accusamus minima totam sed aspernatur quibusdam commodi, quaerat mollitia nobis?
                        Dolore labore consectetur excepturi nesciunt quisquam voluptates ad vitae fugit provident aliquid ex, temporibus at dolorem asperiores soluta repellat cum maxime quaerat! Veritatis obcaecati officiis iste? Aut, repudiandae. At, facilis?</p>
                    </div>
                </div>
            </div>
            <br><br>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/Login.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Logout</title>
    </head>
    <body>
        <div class="container-xxl">
            <div class="row">
                <div class="mb-3">
                    <br>
                </div>
                <center>
                    <div class="col-4">
                        <div class="wrapper">
                            <h2 class="tituloformulario">Login</h2>
                            {{error}}
                            <form action="" method="POST">
                                {% csrf_token %}
                                <center>
                                    <div class="input-box">
                                        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username" placeholder="Username">
                                        <i class='bx bxs-user'></i>
                                    </div>
                                    <div class="input-box">
                                        <input type="password" name="password" autocomplete="current-password" required="" id="id_password" placeholder="Password">
                                        <i class='bx bxs-lock-alt' ></i>
                                    </div>
                                    <button class="btn btn-primary">Login</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </center>
            </div>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/Signup.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Hello</title>
    </head>
    <body>
        <div class="container-xxl">
            <div class="row">
                <div class="mb-3">
                    <br>
                </div>
                <center>
                    <div class="col-5">
                        <div class="wrapper">
                            <h2 class="tituloformulario">Signup</h2>
                            {{error}}
                            <form method="POST">
                                {% csrf_token %}
                                <center>
                                    <div class="input-box">
                                        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" aria-describedby="id_username_helptext" id="id_username" placeholder="Username">
                                        <i class='bx bxs-user'></i>
                                    </div> 
                                    <div class="input-box">
                                        <input type="password" name="password1" autocomplete="new-password" required="" aria-describedby="id_password1_helptext" id="id_password1" placeholder="Password">
                                        <i class='bx bxs-lock-alt' ></i>
                                    </div>
                                    <div class="input-box">
                                        <input type="password" name="password2" autocomplete="new-password" required="" aria-describedby="id_password2_helptext" id="id_password2" placeholder="Password Confirmation">
                                        <i class='bx bxs-lock-alt' ></i>
                                    </div>
                                    <button class="btn">Signup</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </center>
            </div>
        </div>
       

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/Task_detail.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Tasks</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div><br>
                    <h1 class="titulohome">{{task.title}}</h1>
                    {{error}}
                </div>
                <div class="col-6">
                    <form method="POST">
                        {% csrf_token %}
                        <div>
                            <label class="textdetail1" for="id_title">Title:</label>
                            <input class="inputdetail1" type="text" name="title" value="{{task.title}}" maxlength="100" required="" id="id_title" placeholder="Title">
                        </div><br>
                        <div>
                            <label class="textdetail2" for="id_description">Description:</label>
                            <textarea class="inputdetail2" name="description" cols="40" rows="10" id="id_description" placeholder="Write a description">{{task.description}}</textarea>
                        </div><br>
                        <div>
                            <label class="textdetail1" for="id_important">Important:</label>
                            {% if task.important %}
                            <input class="inputdetail3" type="checkbox" name="important" id="id_important" checked="">
                            {% else %}
                            <input class="inputdetail3" type="checkbox" name="important" id="id_important">
                            {% endif %}
                        </div><br>
                        <button class="btn btn-primary">Save</button>
                    </form>
                    <form action="{% url 'complete_task' task.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-success">Complete</button>
                    </form>
                </div>
            </div>
            <br><br><br>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/Tasks.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Tasks</title>
    </head>
    <body>
        <div class="container-xxl">
            <div class="row">
                <div><br>
                    {% if task.datecompleted %}
                    <h1 class="titulohome">Tasks Completed</h1>
                    {% endif %}
                    <h1 class="titulohome">Tasks Pending</h1>
                </div>
                <div><br>
                    <div class="col-10" style="margin: 0 auto;">
                        <div>
                            <table class="tablatasks">
                                <tr>
                                    <th class="filastasks">Title</th>
                                    <th class="filastasks">Description</th>
                                    <th class="filastasks">Author</th>
                                    {% if task.datecompleted %}
                                    <th class="filastasks">Date Completed</th>
                                    {% endif %}
                                    <th class="filastasks">Options</th>
                                </tr>
                                {% for task in tasks %}
                                <tr>
                                    {% if task.important %}
                                    <td class="columnastasksimport">{{task.title}}</td>
                                    {% else %}
                                    <td class="columnastasks">{{task.title}}</td>
                                    {% endif %}
                                    <td class="columnastasksdesc">{{task.description}}</td>
                                    <td class="columnastasksuser">{{task.user.username}}</td>
                                    {% if task.datecompleted %}
                                    <td class="columnastasks">{{task.datecompleted|date:'M j Y:i'}}</td>
                                    {% endif %}
                                    <td style="border: 1px solid black; text-align: center;">
                                    <a href="{% url 'task_detail' task.id %}"><button class="btn btn-success" style="margin: 5px;">Update</button></a>
                                    <form action="{% url 'delete_task' task.id %}" method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" style="margin: 5px;">Delete</button>
                                    </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>                  
                </div>
            </div>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Style.css' %}">
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <title>Django CRUD</title>
    </head>
    <body>
        <div>
        <header class="header">
            <a href="/" class="logo">Home</a>
                <nav class="navbar">
                    {% if user.is_authenticated %}
                    <a href="/tasks">Tasks Pending</a>
                    <a href="/tasks_completed/">Tasks Completed</a>
                    <a href="/tasks/create/">Create Task</a>
                    <a href="/logout">Logout</a>
                    {% else %}
                    <a href="/signup">Signup</a>
                    <a href="/login">Login</a>
                    {% endif %}
                </nav>
        </header>
    </div>

        {% block content %}
        {% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

tasks/templates/create_task.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Document</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div><br>
                    <h1 class="titulohome">Create task</h1>
                    {{error}}
                </div>
                <div class="col-6">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div>
                            <label class="textdetail1" for="id_title">Title:</label>
                            <input class="inputdetail1" type="text" name="title" maxlength="100" required="" id="id_title" placeholder="Write a title">
                        </div><br>
                        <div>
                            <label class="textdetail2" for="id_description">Description:</label>
                            <textarea class="inputdetail2" name="description" cols="40" rows="10" id="id_description" placeholder="Write a description"></textarea>
                        </div><br>
                        <div>
                            <label class="textdetail1" for="id_important">Important:</label>
                            <input class="inputdetail3" type="checkbox" name="important" id="id_important">
                        </div>
                        <button class="btn btn-success">Success</button>
                    </form>
                </div>
            </div><br><br>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/login.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Logout</title>
    </head>
    <body>
        <div class="container-xxl">
            <div class="row">
                <div class="mb-3">
                    <br>
                </div>
                <center>
                    <div class="col-4">
                        <div class="wrapper">
                            <h2 class="tituloformulario">Login</h2>
                            {{error}}
                            <form action="" method="POST">
                                {% csrf_token %}
                                <center>
                                    <div class="input-box">
                                        <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="username" placeholder="Username">
                                        <i class='bx bxs-user'></i>
                                    </div>
                                    <div class="input-box">
                                        <input type="password" name="password" autocomplete="current-password" required="" id="password" placeholder="Password">
                                        <i class='bx bxs-lock-alt' ></i>
                                    </div>
                                    <button class="btn btn-primary">Login</button>
                                </center>
                            </form>
                        </div>
                    </div>
                </center>
            </div>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}

tasks/templates/task_detail.html
{% extends 'base.html' %}
{% block content %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <title>Tasks</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div><br>
                    <h1 class="titulohome">{{task.title}}</h1>
                    {{error}}
                </div>
                <div class="col-6">
                    <form method="POST">
                        {% csrf_token %}
                        <div>
                            <label class="textdetail1" for="id_title">Title:</label>
                            <input class="inputdetail1" type="text" name="title" value="{{task.title}}" maxlength="100" required="" id="id_title" placeholder="Title">
                        </div><br>
                        <div>
                            <label class="textdetail2" for="id_description">Description:</label>
                            <textarea class="inputdetail2" name="description" cols="40" rows="10" id="id_description" placeholder="Write a description">{{task.description}}</textarea>
                        </div><br>
                        <div>
                            <label class="textdetail1" for="id_important">Important:</label>
                            {% if task.important %}
                            <input class="inputdetail3" type="checkbox" name="important" id="id_important" checked="">
                            {% else %}
                            <input class="inputdetail3" type="checkbox" name="important" id="id_important">
                            {% endif %}
                        </div><br>
                        <button class="btn btn-primary">Save</button>
                    </form>
                    <form action="{% url 'complete_task' task.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-success">Complete</button>
                    </form>
                </div>
            </div>
            <br><br><br>
        </div>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

{% endblock %}